version: '3'
services:
  frontend:
    container_name: todo-frontend
    image: todo-frontend
    depends_on:
      - api
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  api:
    container_name: todo-api
    image: todo-api
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: todo.API/Dockerfile
    ports:
      - 5017:8080
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=TodoDb;User=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;Encrypt=False

  db:
    container_name: todo-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
      - MSSQL_PID=Express
      - MSSQL_DATABASE=TodoDb
    ports:
      - '1433:1433'  # Expose SQL Server port
    volumes:
      - db-data:/var/opt/mssql

volumes:
  db-data:
    driver: local
